<?php

TRUNCATE TABLE public.calle RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.casa RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.categoria RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.discapacidad RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.documento RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.estado_civil RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.hpersona RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.nivel_instruccion RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.perfil RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.usuario RESTART IDENTITY CASCADE;

?>
